### ISSUE TITLE
Convert static module to dynamic module

### ISSUE THREAD

**Issue by edemauro** [cybozu/nginx-uuid4-module#2]
Nginx introduced dynamic modules with 1.9.11 (https://www.nginx.com/resources/wiki/extending/converting/). Would it be possible to convert this module to a dynamic module?

**Comment by ghost** [comment]
We used it for request id, but now nginx officially provides $request_id.
We does not use this module, so we have no plan to convert to a dynamic.

**Comment by lantrix** [comment]
Seem it is done now cybozu/nginx-uuid4-module#3
